WebLab1/WebLab1/Components/CartViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebLab.Extensions;
using WebLab.Models;

namespace WebLab.Components
{
    public class CartViewComponent : ViewComponent
    {
        private Cart _cart;
        public CartViewComponent(Cart cart)
        {
            _cart = cart;
        }
        public IViewComponentResult Invoke()
        {
            //var cart = HttpContext.Session.Get<Cart>("cart");
            return View(_cart);
        }
    }
}

WebLab1/WebLab1/Components/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebLab.Models;

namespace WebLab.Components
{
    public class MenuViewComponent : ViewComponent
    {
        // Инициализация списка элементов меню
        private List<MenuItem> _menuItems = new List<MenuItem>
        {
            new MenuItem{ Controller="Home", Action="Index", Text="Lab 2"},
            new MenuItem{ Controller="Product", Action="Index", Text="Каталог"},
            new MenuItem{ IsPage=true, Area="Admin", Page="/Index", Text="Администрирование"},
            new MenuItem{ IsPage=true, Area="ApiDemo", Page="/Index", Text="API-demo"}
        };

        public IViewComponentResult Invoke()
        {
            //Получение значений сегментов маршрута
            var controller = ViewContext.RouteData.Values["controller"];
            var page = ViewContext.RouteData.Values["page"];
            var area = ViewContext.RouteData.Values["area"];
            foreach (var item in _menuItems)
            {
                // Название контроллера совпадает?
                var _matchController = controller?.Equals(item.Controller)
                ?? false;// Название зоны совпадает?
                var _matchArea = area?.Equals(item.Area) ?? false;
                // Если есть совпадение, то сделать элемент меню активным
                // (применить соответствующий класс CSS)
                if (_matchController || _matchArea)
                {
                    item.Active = "active";
                }
            }
            return View(_menuItems);
        }
    }
}

WebLab1/WebLab1/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using WebLab.DAL.Entities;

namespace WebLab.Controllers
{

    public class ImageController : Controller
    {
        UserManager<ApplicationUser> _userManager;
        IWebHostEnvironment _env;

        public ImageController(UserManager<ApplicationUser> userManager, IWebHostEnvironment env)
        {
            _userManager = userManager;
            _env = env;
        }

        public async Task<FileResult> GetAvatar()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user.AvatarImage != null)
                return File(user.AvatarImage, "image/...");
            else
            {
                var avatarPath = "/Images/anonymous.jpg";
                return File(_env.WebRootFileProvider
                .GetFileInfo(avatarPath)
                .CreateReadStream(), "image/...");
            }
        }
    }
}

WebLab1/WebLab1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebLab1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <div class="container">
            <!-- Панель навигации -->
            <nav class="navbar navbar-expand-md navbar-dark bg-dark">
                <!-- меню сайта -->
                <a class="navbar-brand" asp-action="Index" aspcontroller="Home">90321-2 Лапицкий Ю.Г.</a>
                <div class="navbar-nav">
                    @await Component.InvokeAsync("Menu")
                </div>
                <!-- меню сайта - конец -->
                <!-- Информация пользователя -->
                        <partial name="_UserPartial" />
                <!-- Информация пользователя - конец -->
            </nav> <!-- Панель навигации - конец -->
            <!--<span class="nav-color">Заголовок страницы</span>-->
        </div><!-- container - конец -->
    </header><!-- header - конец -->
    <main class="container">
        @RenderBody()
    </main>
    <footer>
        <div class="container">
            <!--<span class="nav-color">Подвал страницы</span>-->
            <div class="navbar navbar-dark navbar-expand-md bg-dark">
                <div class="navbar-nav ml-auto">
                    <a class="nav-item nav-link" href="http://www.facebook.com">
                        <i class="fab fa-facebook-f fa-2x"></i>
                    </a><a class="nav-item nav-link" href="http://www.vk.com">
                        <i class="fab fa-vk fa-2x"></i>
                    </a>
                    <a class="nav-item nav-link" href="http://www.twitter.com">
                        <i class="fab fa-twitter fa-2x"></i>
                    </a>
                </div>
            </div>
        </div>
        Содержимое страницы
        Панель навигации
        Подвал страницы
    </footer>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebLab1/WebLab1/Views/Shared/_UserPartial.cshtml
@using Microsoft.AspNetCore.Identity;
@using WebLab.DAL.Entities;
@inject SignInManager<ApplicationUser> signInManager

@if (signInManager.IsSignedIn(User))
{
    @await Component.InvokeAsync("Cart")
    <div class="dropdown ml-4 nav-color">
        <div class="dropdown-toggle" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            @*<img src="@Url.Action("GetAvatar","Image")" width="30" alt="User" class="rounded bg-light" />*@

            <img img-action="GetAvatar"
                 img-controller="Image"
                 width="30" alt="User"
                 class="rounded bg-light" />
        </div>

        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <div class="dropdown-item-text">

                <img img-action="GetAvatar"
                     img-controller="Image"
                     width="30" alt="User"
                     class="rounded bg-light" />
                @User.Identity.Name
            </div>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-controller="Cart" aspaction="Index">Мои товары</a>
            <form asp-area="Identity" asp-page="/Account/Logout" asp-route-returnurl="@ViewContext.HttpContext.Request.Path">
                <input type="submit" value="Log off" class="dropdown-item" />
            </form>
        </div>
    </div>
}
else
{
    <ul class="nav navbar-nav ml-auto">
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Login">
                Войти
            </a>
        </li>
        <li>
            <a class="nav-item nav-link"
               asp-area="Identity"
               asp-page="/Account/Register">
                Зарегистрироваться
            </a>
        </li>
    </ul>
}