WebLab1/WebLab1/Areas/ApiDemo/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebLab.Areas.ApiDemo.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

WebLab1/WebLab1/Controllers/PlanesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebLab.DAL.Data;
using WebLab.DAL.Entities;

namespace WebLab.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PlanesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public PlanesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: api/Planes
        [HttpGet]
        public async Task<ActionResult<IEnumerable<Plane>>> GetPlanes(int?group)
        {
            return await _context.Planes.Where(d => !group.HasValue || d.PlaneGroupId.Equals(group.Value))?.ToListAsync();
        }

        // GET: api/Planes/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Plane>> GetPlane(int id)
        {
            var plane = await _context.Planes.FindAsync(id);

            if (plane == null)
            {
                return NotFound();
            }

            return plane;
        }

        // PUT: api/Planes/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutPlane(int id, Plane plane)
        {
            if (id != plane.PlaneId)
            {
                return BadRequest();
            }

            _context.Entry(plane).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PlaneExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Planes
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://go.microsoft.com/fwlink/?linkid=2123754.
        [HttpPost]
        public async Task<ActionResult<Plane>> PostPlane(Plane plane)
        {
            _context.Planes.Add(plane);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetPlane", new { id = plane.PlaneId }, plane);
        }

        // DELETE: api/Planes/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Plane>> DeletePlane(int id)
        {
            var plane = await _context.Planes.FindAsync(id);
            if (plane == null)
            {
                return NotFound();
            }

            _context.Planes.Remove(plane);
            await _context.SaveChangesAsync();

            return plane;
        }

        private bool PlaneExists(int id)
        {
            return _context.Planes.Any(e => e.PlaneId == id);
        }
    }
}

WebLab1/WebLab1/Areas/ApiDemo/Pages/Index.cshtml
@page
@model WebLab.Areas.ApiDemo.Pages.IndexModel
@{
}
<table class="table table-striped table-sm" id="list"></table>
<div class="lead" id="info"></div>

@section Scripts{
    <script>
        var url = "@Url.Action("GetPlanes", "Planes")";
                 $(document).ready(function () {
                     $.getJSON(url, function (data) {       // послать запрос
                         var table = $("#list");                // найти таблицу по id
                         $.each(data, function (num, value) {  // сформировать строку для каждого полученного объекта
                              createRow(num+1, value).appendTo(table);
                         })
                     });
                 })

        function createRow(index, data) { // Функция формирования одной строки таблицы, index - порядковый номер, data - объект данных
            var row = $("<tr>");                                   // создать строку таблицы
            row.append("<td>" + index + "</td>");                  // добавть колонку с порядковым номером
            row.append("<td>" + data.planeName + "</td>");          // добавить колонку с названием
            var button = $("<button>").addClass("btn btn-success") // создать кнопку, стиль кнопки            
                .click(data.planeId, showDetails).text("Подробно"); // подписка на событие click, надпись
            var td = $("<td>").append(button);                     // создать колонку с кнопкой
            row.append(td);                                        // добавить в строку таблицы
            return row;
        }

        function showDetails(e) { //Функция выода информации о выбранном объекте

            $.getJSON(url + "/" + e.data, function (data) {   // Послать запрос
                var details = data.planeName + ": " + data.description + " - " + data.speed + " км/ч"; // строка информации об объекте
                $("#info").empty().text(details);   // Найти блок для информации, очистить содержимое, записать новый текст
            })
        }
    </script>
}