WebLab1/WebLab1/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebLab.DAL.Data;
using WebLab.Extensions;
using WebLab.Models;

namespace WebLab.Controllers
{
    public class CartController : Controller
    {
        private ApplicationDbContext _context;
        private Cart _cart;
        private string cartKey = "cart";
        public CartController(ApplicationDbContext context, Cart cart)
        {
            _context = context;
            _cart = cart;
        }
        public IActionResult Index()
        {
            return View(_cart.Items.Values);
        }
        [Authorize]
        public IActionResult Add(int id, string returnUrl)
        {
            var item = _context.Planes.Find(id);
            if (item != null)
            {
                _cart.AddToCart(item);
            }
            return Redirect(returnUrl);
        }

        public IActionResult Delete(int id)
        {
            _cart.RemoveFromCart(id);
            return RedirectToAction("Index");
        }
    }
}

WebLab1/WebLab1/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using WebLab.DAL.Entities;
using WebLab.Models;
using WebLab.Extensions;
using WebLab.DAL.Data;
using Castle.Core.Logging;
using Microsoft.Extensions.Logging;
using ILogger = Microsoft.Extensions.Logging.ILogger;

namespace WebLab.Controllers
{
    public class ProductController : Controller
    {
        ApplicationDbContext _context;
        int _pageSize;

        private ILogger _logger;
        //public ProductController(ApplicationDbContext context, ILogger<ProductController> logger)//---------------------
        //{
        //    _pageSize = 3;
        //    _context = context;
        //    _logger = logger;
        //}
        public ProductController(ApplicationDbContext context)
        {
            _pageSize = 3;
            _context = context;            
        }
       
        [Route("Catalog")]
        [Route("Catalog/Page_{pageNo}")]
        //public IActionResult Index(int? group, int pageNo)//--------------------------------
        public IActionResult Index(int? group, int pageNo=1)
        {
            var groupName = group.HasValue ? _context.PlaneGroups.Find(group.Value)?.GroupName : "all groups";
            //_logger.LogInformation($"info: group={group}, page={pageNo}");//ошибка
            var planesFiltered = _context.Planes.Where(d => !group.HasValue || d.PlaneGroupId == group.Value);

           
        
            
            // Поместить список групп во ViewData
            ViewData["Groups"] = _context.PlaneGroups;
            //var planesFiltered = _planes.Where(d => !group.HasValue || d.PlaneGroupId == group.Value);
            //ViewData["Groups"] = _planeGroups; // Поместить список групп во ViewData            
            ViewData["CurrentGroup"] = group ?? 0; // Получить id текущей группы и поместить в TempData

            var model = ListViewModel<Plane>.GetModel(planesFiltered, pageNo,_pageSize);
            //if (Request.Headers["x-requested-with"].ToString().ToLower().Equals("xmlhttprequest"))
            //    return PartialView("_listpartial", model);
            if (Request.IsAjaxRequest())
                return PartialView("_listpartial", model);
            else
                return View(model);
        }



        /// <summary>
        /// Инициализация списков
        /// </summary>

        //private void SetupData()
        //{
        //    _planeGroups = new List<PlaneGroup>
        //    {
        //        new PlaneGroup {PlaneGroupId=1, GroupName="Планеры"},
        //        new PlaneGroup {PlaneGroupId=2, GroupName="Пассажирские"},
        //        new PlaneGroup {PlaneGroupId=3, GroupName="Частные"},
        //        new PlaneGroup {PlaneGroupId=4, GroupName="Истребители"},
        //        new PlaneGroup {PlaneGroupId=5, GroupName="Бомбордировщики"},
        //        new PlaneGroup {PlaneGroupId=6, GroupName="Штурмовики"}
        //    };
        //    _planes = new List<Plane>
        //    {
        //        new Plane {PlaneId = 1, PlaneName="А320", Description="Максимальное количество пассажиров - 180", Speed =840, PlaneGroupId=2, Image="А320.jpg" },
        //        new Plane {PlaneId = 2, PlaneName="RF-01", Description="Летит без двигателя", Speed =250, PlaneGroupId=1, Image="planer.jpg" },
        //        new Plane {PlaneId = 3, PlaneName="Cessna-172", Description="Самый массовый самолет в истории авиации", Speed =226, PlaneGroupId=3, Image="Cessna_172rg.jpg" },
        //        new Plane {PlaneId = 4, PlaneName="B-2 Spirit", Description="Самый незаметный бомбардировщик в мире", Speed =1010, PlaneGroupId=5, Image="b-2_spirit.jpg" },
        //        new Plane {PlaneId = 5, PlaneName="МиГ-25", Description="Самый быстрый истребитель", Speed =3395, PlaneGroupId=4, Image="Миг-25.jpg" }
        //    };
        //}
    }
}
        

WebLab1/WebLab1/Views/Product/Index.cshtml
@using WebLab.Models;
@model ListViewModel<Plane>


@{
    ViewData["Title"] = "Каталог";

    var categories = ViewData["Groups"] as IEnumerable<PlaneGroup>;
    int currentGroup = (int)ViewData["CurrentGroup"];
    var text = currentGroup !=0 ? categories.FirstOrDefault(g => g.PlaneGroupId == currentGroup)?.GroupName : "Все";
 } 

<div class="row">
    <div class="col-2">
        <div class="dropdown mt-2">
            <a class="btn btn-secondary dropdown-toggle"
               asp-action="Index" asp-controller="Product"
               role="button"
               id="dropdownMenuLink"
               data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                @text
            </a>
            <div class="dropdown-menu"
                 aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item"
                   asp-action="Index"
                   asp-controller="Product">Все</a>
                @foreach (var item in categories)
                {
                    <a class="dropdown-item"
                       asp-action="Index"
                       asp-controller="Product"
                       asp-route-group="@item.PlaneGroupId"
                       asp-route-pageNo="1">@item.GroupName</a>
                }
            </div>
        </div>
    </div>
    <div class="card-group" id="list">
        <partial name="_ListPartial" model="@Model" />
    </div>
    
    <pager page-current="@Model.CurrentPage"
           page-total="@Model.TotalPages"
           action="Index"
           controller="Product"
           group-id="@currentGroup"></pager>
</div>       
    
   

   




















    @*<h1>Index</h1>

        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.DishId)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DishName)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Calories)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Image)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.DishGroupId)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.DishId)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DishName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Calories)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Image)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DishGroupId)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                        </td>
                    </tr>
                }
            </tbody>
        </table>*@

WebLab1/WebLab1/Views/Product/_ListItemPartial.cshtml
@model Plane
<div class='card m-2 p-1 text-center col-4'>
    <img src="~/Images/@Model.Image"
         alt='NoImage' class="card-img-top" />
    <div class="card-body">
        <h5 class="card-title">
            @Model.PlaneName
        </h5>
        <p class="card-text">
            @Model.Description
        </p>
        <div class="card-text badge badge-secondary">
            <h6>@Model.Speed км/ч</h6>
        </div>
        @{ // Получение текущего адреса
            var request = ViewContext.HttpContext.Request;
            var returnUrl = request.Path +
            request.QueryString.ToUriComponent();
        }
        <!--Разметка кнопки добавления в корзину-->
        <p class="mt-2">
            <a asp-action="Add"
               asp-controller="Cart"
               asp-route-id="@Model.PlaneId"
               asp-route-returnUrl="@returnUrl"
               class="btn btn-primary">
                <i class="fa fa-shopping-cart"></i> В корзину
            </a>
        </p>
    </div>
</div>

WebLab1/WebLab1/Views/Product/_ListPartial.cshtml
@model ListViewModel<Plane>
@foreach (var item in Model)
{
    <partial name="_ListItemPartial" model="@item" />
}